using Microsoft.EntityFrameworkCore;

namespace DietSentry;

public class FoodsContext : DbContext
{
    public DbSet<Food> Foods { get; set; }
    public DbSet<Eaten> Eaten { get; set; }
    public DbSet<Recipe> Recipe { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=foods.db");
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Eaten>().HasData(
            new Eaten
            {
                EatenId = 1,
                DateEaten = "29-Aug-2023",
                TimeEaten = "15:15",
                EatenTs = 8291515,
                AmountEaten = 100.0F,
                FoodDescription = "Test 1",
                Energy = 1.01F,
                Protein = 2.11F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            },
            new Eaten
            {
                EatenId = 2,
                DateEaten = "29-Aug-2023",
                TimeEaten = "15:20",
                EatenTs = 8291520,
                FoodDescription = "Test 2",
                Energy = 2.0F,
                Protein = 2.0F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            },
            new Eaten
            {
                EatenId = 3,
                DateEaten = "31-Aug-2023",
                TimeEaten = "16:20",
                EatenTs = 8311620,
                FoodDescription = "Test 3",
                Energy = 1.01F,
                Protein = 2.11F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            },
            new Eaten
            {
                EatenId = 4,
                DateEaten = "1-Sep-2023",
                TimeEaten = "09:03",
                EatenTs = 9010903,
                FoodDescription = "Test 4",
                Energy = 1.0F,
                Protein = 2.0F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            }
        );

        modelBuilder.Entity<Food>().HasData(
            new Food
            {
                FoodId = 1,
                FoodDescription = "Test 1",
                Energy = 1.01F,
                Protein = 2.11F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            },
            new Food
            {
                FoodId = 2,
                FoodDescription = "Test 2",
                Energy = 2.0F,
                Protein = 2.0F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            },
            new Food
            {
                FoodId = 3,
                FoodDescription = "Test 2",
                Energy = 1.0F,
                Protein = 2.0F,
                FatTotal = 3.0F,
                SaturatedFat = 4.0F,
                TransFat = 5.0F,
                PolyunsaturatedFat = 6.0F,
                MonounsaturatedFat = 7.0F,
                Carbohydrate = 8.0F,
                Sugars = 9.0F,
                DietaryFibre = 10.0F,
                SodiumNa = 11.0F,
                CalciumCa = 12.0F,
                PotassiumK = 13.0F,
                ThiaminB1 = 14.0F,
                RiboflavinB2 = 15.0F,
                NiacinB3 = 16.0F,
                Folate = 17.0F,
                IronFe = 18.0F,
                MagnesiumMg = 19.0F,
                VitaminC = 20.0F,
                Caffeine = 21.0F,
                Cholesterol = 22.0F,
                Alcohol = 23.0F
            }
        );

    }
}

